homework 1 (form)
polina-ivanova/react-andersen pull request #1
Opened 2022-12-12 08:45 UTC by polina-ivanova

2022-12-12 09:14 UTC, darya-startsava requested changes
Code looks very cood, exept 1 remark with key. I can not evaluate design without deploy. I think it's a good job according requirements. I'll approve it after fixing keys-issue.

2022-12-12 09:14 UTC, darya-startsava commented on src/Components/Form/Form.js
> +                  <Input label={input.label} placeholder={input.placeholder} />
we have to use keys when work witn lists.
https://reactjs.org/docs/lists-and-keys.html

2022-12-12 09:14 UTC, darya-startsava commented on src/Components/Form/Form.js
> +                  <Textarea
The same remars as above, keys

2022-12-12 09:48 UTC, polina-ivanova commented on src/Components/Form/Form.js
> +                  <Textarea
Ok, I fixed it

2022-12-12 12:28 UTC, darya-startsava approved these changes

2022-12-14 19:09 UTC, poulkud requested changes

2022-12-14 19:09 UTC, poulkud commented on src/App.js
> +      <>
фрагмент тут не нужен

2022-12-14 19:09 UTC, poulkud commented on src/Components/Button/Button.js
> +      <>
тут тоже не надо

2022-12-14 19:09 UTC, poulkud commented on src/Components/Form/Form.js
> +      <>
тернарник тут не обязателен

2022-12-14 19:09 UTC, poulkud commented on src/Components/Form/Form.js
> +              {" "}
а что за отступ? сделай через стили если он нужен

2022-12-14 19:09 UTC, poulkud commented on src/Components/Input/Input.js
> +      <>
тернарник)

2022-12-14 19:09 UTC, poulkud commented on src/Components/Textarea/Textarea.js
> +        {" "}
что за пробел ?

2022-12-14 19:09 UTC, poulkud commented on src/Components/Textarea/Textarea.js
> +        {" "}
тернарник лишний

2022-12-20 19:28 UTC, poulkud approved these changes

2022-12-20 19:46 UTC, merged